#if !canImport(ObjectiveC)
import XCTest

extension SwiftLinuxStatTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftLinuxStatTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftLinuxStatTests.__allTests__SwiftLinuxStatTests),
    ]
}
#endif
